"""
Change column name from link to url

Revision ID: 11b0d8988b1d
Revises: 50505ee6888a
Create Date: 2014-12-24 14:26:41.615193

"""

# revision identifiers, used by Alembic.
revision = '11b0d8988b1d'
down_revision = '50505ee6888a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependency', column_name='link', new_column_name='url',
                    existing_nullable=True, existing_type=sa.String(length=255))
    op.alter_column('license', column_name='link', new_column_name='url',
                    existing_nullable=True, existing_type=sa.String(length=255))
    op.alter_column('package', column_name='link', new_column_name='url',
                    existing_nullable=True, existing_type=sa.String(length=140))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', column_name='url', new_column_name='link',
                    existing_nullable=True, existing_type=sa.String(length=140))
    op.alter_column('license', column_name='url', new_column_name='link',
                    existing_nullable=True, existing_type=sa.String(length=255))
    op.alter_column('dependency', column_name='url', new_column_name='link',
                    existing_nullable=True, existing_type=sa.String(length=255))
    ### end Alembic commands ###
