"""empty message

Revision ID: 1da1fd2bd9b5
Revises: 599d2b8d6a75
Create Date: 2014-12-21 22:54:52.074008

"""

# revision identifiers, used by Alembic.
revision = '1da1fd2bd9b5'
down_revision = '599d2b8d6a75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_flags')
    ### end Alembic commands ###
