"""
Keywords table added

Revision ID: 46f360cc7a28
Revises: 11b0d8988b1d
Create Date: 2014-12-27 19:32:46.683041

"""

# revision identifiers, used by Alembic.
revision = '46f360cc7a28'
down_revision = '11b0d8988b1d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], )
    )
    op.drop_column(u'package', 'keywords')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'package', sa.Column('keywords', mysql.TEXT(), nullable=True))
    op.drop_table('keywords')
    op.drop_table('keyword')
    ### end Alembic commands ###
