"""
Create license, dependency tables
Add stars, keywords to package

Revision ID: 50505ee6888a
Revises: 589962765a19
Create Date: 2014-12-24 00:42:33.975402

"""

# revision identifiers, used by Alembic.
revision = '50505ee6888a'
down_revision = '589962765a19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('dependency_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], )
    )
    op.add_column(u'package', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column(u'package', sa.Column('license_id', sa.Integer(), nullable=True))
    op.add_column(u'package', sa.Column('stars', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'package', 'stars')
    op.drop_column(u'package', 'license_id')
    op.drop_column(u'package', 'keywords')
    op.drop_table('dependencies')
    op.drop_table('license')
    op.drop_table('dependency')
    ### end Alembic commands ###
