"""empty message

Revision ID: 589962765a19
Revises: 1da1fd2bd9b5
Create Date: 2014-12-22 20:01:20.435496

"""

# revision identifiers, used by Alembic.
revision = '589962765a19'
down_revision = '1da1fd2bd9b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    ### end Alembic commands ###
