"""date unique removed

Revision ID: 599d2b8d6a75
Revises: 1e01803baf30
Create Date: 2014-09-27 00:51:12.568251

"""

# revision identifiers, used by Alembic.
revision = '599d2b8d6a75'
down_revision = '1e01803baf30'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'date', 'downloads', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'date', 'downloads', ['date'])
    ### end Alembic commands ###
